{{- if .Values.tracing.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.tracing.secrets.name }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  ca-cert.pem: {{ .Values.tracing.certs.ca }}
  client-cert-key.pem: {{ .Values.tracing.certs.client }}
  client-cert.pem: {{ .Values.tracing.certs.key }}
type: Opaque
{{- if .Values.secrets.immutable.enabled }}
immutable: true
{{- end }}
{{- end }}
