apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
  labels: {{- include "backend.labels" . | nindent 4 }}
type: Opaque
{{- if .Values.secrets.immutable.enabled }}
immutable: true
{{- end }}
data:
  PGUSER: {{ default "" .Values.db.PGUSER | b64enc | quote }}
  PGPASSWORD: {{ default "" .Values.db.PGPASSWORD | b64enc | quote }}
  KEYCLOAK_USER: {{ default "" .Values.keycloak.KEYCLOAK_USER | b64enc | quote }}
  KEYCLOAK_PWD: {{ default "" .Values.keycloak.KEYCLOAK_PWD | b64enc | quote }}
  BPMN_USER: {{ default "" .Values.bpmn.BPMN_USER | b64enc | quote }}
  BPMN_PWD: {{ default "" .Values.bpmn.BPMN_PWD | b64enc | quote }}
  BPMN_KEY: {{ default "" .Values.bpmn.BPMN_KEY | b64enc | quote }}
