const sql = `
    SELECT * FROM ARTEFACT_VALUES av INNER JOIN ARTEFACT_REALIZATIONS ar ON av.ARTEFACT_VALUE_ID = ar.ARTEFACT_VALUE_ID 
    WHERE MODEL_ID=:MODEL_ID AND ar.ARTEFACT_ID=:ARTEFACT_ID AND ar.EFFECTIVE_TO > CURRENT_TIMESTAMP
`

module.exports = sql
