const sql = `
SELECT a.ARTEFACT_LABEL, ar.ARTEFACT_STRING_VALUE
FROM ARTEFACT_REALIZATIONS ar
         INNER JOIN ARTEFACTS a ON a.ARTEFACT_ID = ar.ARTEFACT_ID
WHERE ar.MODEL_ID = :MODEL_ID
  AND a.IS_CLASS_FLG = '1'
  AND ar.EFFECTIVE_TO = (
    SELECT MAX(EFFECTIVE_TO)
    FROM ARTEFACT_REALIZATIONS ar
             INNER JOIN ARTEFACTS a ON a.ARTEFACT_ID = ar.ARTEFACT_ID
    WHERE ar.MODEL_ID = :MODEL_ID
      AND a.IS_CLASS_FLG = '1')
`

module.exports = sql
