const sql = `
SELECT ar.ARTEFACT_STRING_VALUE FROM ARTEFACT_REALIZATIONS ar 
    INNER JOIN ARTEFACTS a ON ar.ARTEFACT_ID = a.ARTEFACT_ID 
    WHERE ar.MODEL_ID = :MODEL_ID AND a.ARTEFACT_TYPE_ID IN (2,7,9,10)
`
module.exports = sql