/* 
    Должен возвращаться всю информацию о задаче по ее TASK_ID и MODEL_ID
	При выборке артефактов необходимо получить последнее НЕ NULL значение для предзаполнения формы задачи
*/

const sql = `
WITH ranked_artefact_realizations AS (
	SELECT *, ROW_NUMBER() OVER(
		PARTITION BY 
			ar2.artefact_id, 
			ar2.model_id 
		ORDER BY 
			(ar2.artefact_string_value IS NULL and ar2.artefact_value_id IS NULL) ASC, 
			ar2.effective_to DESC
		) AS RN 
	FROM artefact_realizations ar2
)
SELECT 
	T.TASK_ID,
	T.TASK_NAME,
	AR.ARTEFACT_ID,
	AR.ARTEFACT_CONTEXT,
	AR.ARTEFACT_TECH_LABEL,
	AR.ARTEFACT_LABEL,
	AR.ARTEFACT_DESC,
	AR.ARTEFACT_CONTEXT,
	AR.ARTEFACT_HINT,
	AR.ARTEFACT_REGULAR_EXPRESSION,
	AR.IS_MAIN_INFO_FLG,
	AR.IS_MULTI_FILL_FLG,
	AR.IS_CLASS_FLG,
	AR.ARTEFACT_DEFAULT_VALUE,
	AR.IS_DEFAULT_VALUE_FLG,
	TA.IS_REQUIRED_FLG,
	TA.ARTEFACT_IO_TYPE,
	AR.ARTEFACT_TYPE_ID,
	AR_T.ARTEFACT_TYPE_DESC,
	AR_V.ARTEFACT_VALUE_ID,
	AR_V.ARTEFACT_VALUE_LABEL,
	AR_V.ARTEFACT_PARENT_VALUE_ID,
	AR_V.ARTEFACT_VALUE,
	AR_R.ARTEFACT_VALUE_ID AS CURRENT_ARTEFACT_VALUE_ID,
	AR_R.ARTEFACT_STRING_VALUE AS CURRENT_ARTEFACT_STRING_VALUE,
	AR_R.ARTEFACT_ORIGINAL_VALUE AS CURRENT_ARTEFACT_ORIGINAL_VALUE,
	M.MODEL_ID,
	M.ROOT_MODEL_ID,
	M.MODEL_VERSION
FROM TASKS T

INNER JOIN TASKS_ARTEFACTS TA
	ON T.TASK_ID = TA.TASK_ID
	and TA.DEPLOYMENT_ID = :DEPLOYMENT_ID

INNER JOIN ARTEFACTS AR
	ON TA.ARTEFACT_ID = AR.ARTEFACT_ID

LEFT JOIN ARTEFACT_VALUES AR_V
	ON AR.ARTEFACT_ID = AR_V.ARTEFACT_ID
		AND AR_V.IS_ACTIVE_FLG = '1'

INNER JOIN ARTEFACT_X_TYPE AR_T
	ON AR.ARTEFACT_TYPE_ID = AR_T.ARTEFACT_TYPE_ID

LEFT JOIN ranked_artefact_realizations AR_R
	ON AR.ARTEFACT_ID = AR_R.ARTEFACT_ID
		AND AR_R.MODEL_ID = :MODEL_ID
			AND COALESCE(AR_V.ARTEFACT_VALUE_ID, 0) = COALESCE(AR_R.ARTEFACT_VALUE_ID, 0)
				AND AR_R.RN = 1

LEFT JOIN MODELS M
	ON m.MODEL_ID = :MODEL_ID

WHERE T.TASK_ID = :id
ORDER BY
	T.TASK_ID,
	AR.ARTEFACT_ID,
	AR_V.ARTEFACT_VALUE_ID
`

module.exports = sql