const sql = `
SELECT 
  M.MODEL_ID,
  M.MODEL_NAME,
  M.ROOT_MODEL_ID,
  M.MODEL_VERSION,
  TO_CHAR(M_UPD.UPDATE_DATE, 'DD.MM.YYYY HH24:MI:SS') AS UPDATE_DATE,
  COALESCE(M.MODEL_STAGE, STATUS.BPMN_KEY_DESC) AS STATUS
FROM MODELS M
LEFT JOIN (
  SELECT MODEL_ID, MAX(EFFECTIVE_FROM) AS UPDATE_DATE
  FROM ARTEFACT_REALIZATIONS
  GROUP BY MODEL_ID
) M_UPD ON M.MODEL_ID = M_UPD.MODEL_ID
LEFT JOIN (
  SELECT * FROM (
    SELECT 
      MODEL_ID,
      BPMN_KEY_DESC,
      ROW_NUMBER() OVER (
        PARTITION BY model_id 
        ORDER BY effective_to DESC, effective_from DESC
      ) AS rn
    FROM BPMN_INSTANCES BI
    LEFT JOIN BPMN_PROCESSES BP ON BI.BPMN_KEY_ID = BP.BPMN_KEY_ID
    WHERE BI.EFFECTIVE_TO = TO_TIMESTAMP('9999-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS')
  ) sub
  WHERE rn = 1
) STATUS ON STATUS.MODEL_ID = M.MODEL_ID
WHERE M.MODEL_ID = ANY(:modelIds::text[])
  AND (
    :dateOfDelay::text IS NULL OR 
    TO_TIMESTAMP(CAST(M_UPD.UPDATE_DATE AS TEXT), 'YYYY-MM-DD HH24:MI:SS') 
      <= TO_TIMESTAMP(:dateOfDelay::text, 'YYYY-MM-DD HH24:MI:SS')
  )
`

module.exports = sql;
