/*
    ARTEFACT_ID: 234
    ARTEFACT_TECH_LABEL: 'asdg'
    ARTEFACT_LABEL: 'asdga'
    ARTEFACT_DESC: 'asgd'
    ARTEFACT_TYPE_ID: 4
*/

const sql = `
MERGE INTO ARTEFACTS x
USING 
  (
    SELECT 
        :ARTEFACT_ID as ARTEFACT_ID, 
        :ARTEFACT_TECH_LABEL as ARTEFACT_TECH_LABEL, 
        :ARTEFACT_LABEL as ARTEFACT_LABEL,
        :ARTEFACT_DESC as ARTEFACT_DESC,
        :ARTEFACT_TYPE_ID as ARTEFACT_TYPE_ID,
        :IS_MAIN_INFO_FLG as IS_MAIN_INFO_FLG,
        :IS_CLASS_FLG as IS_CLASS_FLG,
        :IS_EDIT_FLG as IS_EDIT_FLG
    from dual
  ) y
ON (x.ARTEFACT_ID  = y.ARTEFACT_ID)
WHEN MATCHED THEN
    UPDATE SET 
      x.ARTEFACT_LABEL = y.ARTEFACT_LABEL, 
      x.ARTEFACT_DESC = y.ARTEFACT_DESC,
      x.ARTEFACT_TYPE_ID = y.ARTEFACT_TYPE_ID,
      x.IS_MAIN_INFO_FLG = y.IS_MAIN_INFO_FLG,
      x.IS_EDIT_FLG = y.IS_EDIT_FLG
WHEN NOT MATCHED THEN
    INSERT(x.ARTEFACT_ID, x.ARTEFACT_TECH_LABEL, x.ARTEFACT_LABEL, x.ARTEFACT_DESC, x.ARTEFACT_TYPE_ID)  
    VALUES(y.ARTEFACT_ID, y.ARTEFACT_TECH_LABEL, y.ARTEFACT_LABEL, y.ARTEFACT_DESC, y.ARTEFACT_TYPE_ID)
`

module.exports = sql