const sql = `
    SELECT 
        AR_V.ARTEFACT_VALUE_ID,
        AR_V.ARTEFACT_VALUE_LABEL,
        AR_V.ARTEFACT_PARENT_VALUE_ID,
        AR_V.ARTEFACT_VALUE
    FROM ARTEFACTS AR
    LEFT JOIN ARTEFACT_VALUES AR_V
        ON AR.ARTEFACT_ID = AR_V.ARTEFACT_ID
            AND AR_V.IS_ACTIVE_FLG = '1'
    WHERE AR.ARTEFACT_ID = :ARTEFACT_ID
`

module.exports = sql
