const sql = `
  SELECT ARTEFACT_ID,
        ARTEFACT_STRING_VALUE
  FROM ARTEFACT_REALIZATIONS
  WHERE MODEL_ID = :MODEL_ID
    AND ARTEFACT_ID = :ARTEFACT_ID
    AND ARTEFACT_STRING_VALUE = :ARTEFACT_STRING_VALUE
    AND EFFECTIVE_TO = TO_TIMESTAMP('9999-12-3123:59:59', 'YYYY-MM-DDHH24:MI:SS')
`

module.exports = sql
