const sql = `
  SELECT DISTINCT
      M.MODEL_ID as automl_model_id,
      AR1.ARTEFACT_STRING_VALUE as automl_model_customer,
      AR2.ARTEFACT_STRING_VALUE as automl_flg
  FROM
      MODELS M
  LEFT JOIN
      ARTEFACT_REALIZATIONS AR1
      ON M.MODEL_ID = AR1.MODEL_ID
          AND AR1.ARTEFACT_ID = 309
          AND AR1.EFFECTIVE_TO =  TO_TIMESTAMP('9999-12-3123:59:59','YYYY-MM-DDHH24:MI:SS')
  LEFT JOIN
      ARTEFACT_REALIZATIONS AR2
      ON M.MODEL_ID = AR2.MODEL_ID
          AND AR2.ARTEFACT_ID = 310
          AND AR2.EFFECTIVE_TO =  TO_TIMESTAMP('9999-12-3123:59:59','YYYY-MM-DDHH24:MI:SS')
`;

module.exports = sql;
