module.exports = {
  all: require('./all'),
  one: require('./one'),
  instance: require('./instance'),
  artefact: require('./artefact'),
  version: require('./version'),
  new: require('./new'),
  info: require('./info'),
  parent: require('./parent'),
  copy: require('./copy'),
  status: require('./all-status'),
  cancel: require('./cancel'),
  risk: require('./risk'),
  assignments: require('./assignments'),
  artefacts: require('./artefacts'),
  modelsByBpmnIds: require('./modelsByBpmnIds'),
  autoMLRootModel: require('./autoMLRootModel'),
  edit_name: require('./edit_name'),
  edit_desc: require('./edit_desc'),
}
