module.exports = {
  all: require("./all"),
  one: require("./one"),
  instance: require("./instance"),
  artefact: require("./artefact"),
  version: require("./version"),
  new: require("./new"),
  info: require("./info"),
  parent: require("./parent"),
  copy: require("./copy"),
  status: require("./all-status"),
  cancel: require("./cancel"),
  risk: require("./risk"),
  assignments: require("./assignments"),
  artefacts: require("./artefacts"),
  modelsByBpmnIds: require("./modelsByBpmnIds"),
  autoMLRootModel: require("./autoMLRootModel"),
  rootModelByGeneralModelId: require("./rootModelByGeneralModelId"),
  edit_name: require("./edit_name"),
  insert_model_desc_realization: require("./insert_model_desc_realization"),
  update_model_desc_realization: require("./update_model_desc_realization"),
  edit_status: require("./edit_status"),
  edit_stage: require("./edit_stage"),
  edit_desc: require("./edit_desc"),
  edit_active_status: require("./edit_active_status"),
  selectModelForUpdate: require("./selectModelForUpdate"),
};
