const sql = `
    INSERT INTO ARTEFACT_REALIZATIONS (
        MODEL_ID, ARTEFACT_ID, ARTEFACT_STRING_VALUE, EFFECTIVE_FROM, EFFECTIVE_TO
    )
    VALUES (
        :MODEL_ID, 905, :MODEL_DESC, CURRENT_TIMESTAMP, 
        TO_TIMESTAMP('9999-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS')
    );
`;

module.exports = sql;
