const sql = `
    SELECT
        AR_.ARTEFACT_ID,
        AR_.ASSIGNMENT_ID,
        AR_.ARTEFACT_VALUE_ID,
        AR_.ARTEFACT_STRING_VALUE,
        AR_.ARTEFACT_ORIGINAL_VALUE,
        AR_.CREATOR,
        AR_.EFFECTIVE_FROM,
        AR_.EFFECTIVE_TO,
        A_.ARTEFACT_TECH_LABEL,
        A_.ARTEFACT_LABEL,
        A_.ARTEFACT_DESC,
        A_.ARTEFACT_CONTEXT,
        A_.IS_MAIN_INFO_FLG,
        A_.IS_CLASS_FLG,
        A_.ARTEFACT_TYPE_ID,
        A_.ARTEFACT_BUSINESS_GROUP_ID,
        AV_.ARTEFACT_VALUE,
        AV_.IS_ACTIVE_FLG,
        AV_.ARTEFACT_PARENT_VALUE_ID,
        AT_.ARTEFACT_TYPE_DESC,
        TA.IS_REQUIRED_FLG
    FROM
        ASSIGNMENT_ARTEFACT_REALIZATIONS AR_
    INNER JOIN
        ARTEFACTS A_
    ON
        AR_.ARTEFACT_ID = A_.ARTEFACT_ID
    LEFT JOIN
            ARTEFACT_VALUES AV_
        ON
            AR_.ARTEFACT_VALUE_ID = AV_.ARTEFACT_VALUE_ID
    INNER JOIN
            ARTEFACT_X_TYPE AT_
        ON
            A_.ARTEFACT_TYPE_ID = AT_.ARTEFACT_TYPE_ID
    INNER JOIN
            TASKS_ARTEFACTS TA
        ON
            AR_.ARTEFACT_ID = TA.ARTEFACT_ID
    WHERE
            AR_.ASSIGNMENT_ID = ANY (:assignmentsIds::int[])
    AND
        AR_.EFFECTIVE_TO = TO_TIMESTAMP('9999-12-3123:59:59','YYYY-MM-DDHH24:MI:SS')
`

module.exports = sql
