const sql = `
    UPDATE 
        ASSIGNMENT_ARTEFACT_REALIZATIONS
    SET
        ARTEFACT_VALUE_ID = :ARTEFACT_VALUE_ID,
        ARTEFACT_STRING_VALUE = :ARTEFACT_STRING_VALUE,
        ARTEFACT_ORIGINAL_VALUE = :ARTEFACT_ORIGINAL_VALUE
    WHERE 
        ASSIGNMENT_ID= :ASSIGNMENT_ID 
    AND 
        ARTEFACT_ID = :ARTEFACT_ID
`

module.exports = sql
