const sql = `
  SELECT
    ARTEFACT_STRING_VALUE
  FROM
    ASSIGNMENT_ARTEFACT_REALIZATIONS
  WHERE
    ARTEFACT_ID = :ARTEFACT_ID
  GROUP BY
    ARTEFACT_STRING_VALUE
  UNION ALL
  SELECT
    ARTEFACT_STRING_VALUE
  FROM
    ARTEFACT_REALIZATIONS ar
  WHERE
    ARTEFACT_ID = :ARTEFACT_ID
  GROUP BY
    ARTEFACT_STRING_VALUE
`

module.exports = sql
