const sql = `
    UPDATE 
        ASSIGNMENT_ARTEFACT_REALIZATIONS
    SET
        EFFECTIVE_TO=CURRENT_TIMESTAMP(0)
    WHERE 
        ASSIGNMENT_ID=:ASSIGNMENT_ID 
    AND 
        EFFECTIVE_TO=TO_TIMESTAMP('9999-12-3123:59:59','YYYY-MM-DDHH24:MI:SS')
`

module.exports = sql