const sql = `
    UPDATE 
        RISK_SCALE_ARTEFACT_REALIZATIONS
    SET
        ARTEFACT_VALUE_ID = :ARTEFACT_VALUE_ID,
        ARTEFACT_STRING_VALUE = :ARTEFACT_STRING_VALUE
    WHERE
        ARTEFACT_ID = :ARTEFACT_ID
    AND
        ROOT_RISK_SCALE_ID = :ROOT_RISK_SCALE_ID
`

module.exports = sql
