/*
:SYS_SCALE_RANK_ID - ID изменяемой строки
*/


const sql = `
    UPDATE RISK_SCALE_RANKS
    SET
		SCALE_RANK_ID = :SCALE_RANK_ID,
		SCALE_RANK_CAT = :SCALE_RANK_CAT,
		SCALE_RANK_MIN = :SCALE_RANK_MIN,
		SCALE_RANK_AVG = :SCALE_RANK_AVG,
		SCALE_RANK_MAX = :SCALE_RANK_MAX
	WHERE 
		SYS_SCALE_RANK_ID = :SYS_SCALE_RANK_ID
`

module.exports = sql
