const sql = `
    SELECT DISTINCT
        T.TASK_ID,
        T.TASK_NAME,
        AR.ARTEFACT_ID,
        AR.ARTEFACT_CONTEXT,
        AR.ARTEFACT_TECH_LABEL,
        AR.ARTEFACT_LABEL,
        AR.ARTEFACT_DESC,
        AR.ARTEFACT_CONTEXT,
        AR.ARTEFACT_HINT,
        AR.IS_MAIN_INFO_FLG,
        AR.IS_MULTI_FILL_FLG,
        AR.IS_CLASS_FLG,
        AR.ARTEFACT_DEFAULT_VALUE,
        AR.IS_DEFAULT_VALUE_FLG,
        TA.IS_REQUIRED_FLG,
        TA.ARTEFACT_IO_TYPE,
        TA.DEPLOYMENT_ID,
        AR.ARTEFACT_TYPE_ID,
        AR_T.ARTEFACT_TYPE_DESC,
        AR_V.ARTEFACT_VALUE_ID,
        AR_V.ARTEFACT_VALUE_LABEL,
        AR_V.ARTEFACT_PARENT_VALUE_ID,
        AR_V.ARTEFACT_VALUE
    FROM TASKS T
    INNER JOIN TASKS_ARTEFACTS TA
        ON T.TASK_ID = TA.TASK_ID
    INNER JOIN ARTEFACTS AR
        ON TA.ARTEFACT_ID = AR.ARTEFACT_ID
    LEFT JOIN ARTEFACT_VALUES AR_V
        ON AR.ARTEFACT_ID = AR_V.ARTEFACT_ID
            AND AR_V.IS_ACTIVE_FLG = '1'
    INNER JOIN ARTEFACT_X_TYPE AR_T
        ON AR.ARTEFACT_TYPE_ID = AR_T.ARTEFACT_TYPE_ID
    WHERE T.TASK_ID = 'risk_scale_pseudo_task'
    AND TA.DEPLOYMENT_ID = (SELECT max(deployment_id) FROM DEPLOYMENTS)
    ORDER BY
        T.TASK_ID,
        AR.ARTEFACT_ID,
        AR_V.ARTEFACT_VALUE_ID
`

module.exports = sql
