const sql = `
    SELECT
		ROOT_RISK_SCALE_ID,
		SYS_SCALE_RANK_ID,
		SCALE_RANK_ID,
		SCALE_RANK_CAT,
		SCALE_RANK_MIN,
		SCALE_RANK_AVG,
		SCALE_RANK_MAX
	FROM RISK_SCALE_RANKS
    WHERE ROOT_RISK_SCALE_ID = :ROOT_RISK_SCALE_ID
		AND EFFECTIVE_TO = TO_TIMESTAMP('9999-12-3123:59:59','YYYY-MM-DDHH24:MI:SS')
	ORDER BY case when SCALE_RANK_ID ~ '^[[:digit:]]+$' THEN CAST(SCALE_RANK_ID AS INTEGER) ELSE 0 END ASC
`

module.exports = sql
